// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/kv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]uint64      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_proto_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetEntries() map[string]uint64 {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Clock         *VectorClock           `protobuf:"bytes,2,opt,name=clock,proto3" json:"clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Value) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_proto_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type HintedPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *Value                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HintedPutRequest) Reset() {
	*x = HintedPutRequest{}
	mi := &file_proto_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HintedPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintedPutRequest) ProtoMessage() {}

func (x *HintedPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintedPutRequest.ProtoReflect.Descriptor instead.
func (*HintedPutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *HintedPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HintedPutRequest) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HintedPutRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{5}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{7}
}

func (x *GetResponse) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// anti-entropy: exchange key hashes to detect divergence via merkle trees
type KeyHashEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // 16-byte md5 hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyHashEntry) Reset() {
	*x = KeyHashEntry{}
	mi := &file_proto_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyHashEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyHashEntry) ProtoMessage() {}

func (x *KeyHashEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyHashEntry.ProtoReflect.Descriptor instead.
func (*KeyHashEntry) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{8}
}

func (x *KeyHashEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyHashEntry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetKeyHashesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyHashesRequest) Reset() {
	*x = GetKeyHashesRequest{}
	mi := &file_proto_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyHashesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyHashesRequest) ProtoMessage() {}

func (x *GetKeyHashesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyHashesRequest.ProtoReflect.Descriptor instead.
func (*GetKeyHashesRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{9}
}

type GetKeyHashesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KeyHashEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyHashesResponse) Reset() {
	*x = GetKeyHashesResponse{}
	mi := &file_proto_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyHashesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyHashesResponse) ProtoMessage() {}

func (x *GetKeyHashesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyHashesResponse.ProtoReflect.Descriptor instead.
func (*GetKeyHashesResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{10}
}

func (x *GetKeyHashesResponse) GetEntries() []*KeyHashEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// anti-entropy: fetch actual values for divergent keys
type SyncKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncKeysRequest) Reset() {
	*x = SyncKeysRequest{}
	mi := &file_proto_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKeysRequest) ProtoMessage() {}

func (x *SyncKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKeysRequest.ProtoReflect.Descriptor instead.
func (*SyncKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{11}
}

func (x *SyncKeysRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type SyncKeysResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          map[string]*GetResponse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key -> values for that key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncKeysResponse) Reset() {
	*x = SyncKeysResponse{}
	mi := &file_proto_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKeysResponse) ProtoMessage() {}

func (x *SyncKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKeysResponse.ProtoReflect.Descriptor instead.
func (*SyncKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{12}
}

func (x *SyncKeysResponse) GetData() map[string]*GetResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_kv_proto protoreflect.FileDescriptor

const file_proto_kv_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/kv.proto\x12\x02kv\"\x81\x01\n" +
	"\vVectorClock\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.kv.VectorClock.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"B\n" +
	"\x05Value\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12%\n" +
	"\x05clock\x18\x02 \x01(\v2\x0f.kv.VectorClockR\x05clock\"+\n" +
	"\x10HeartbeatMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"?\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.kv.ValueR\x05value\"k\n" +
	"\x10HintedPutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.kv.ValueR\x05value\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\"\r\n" +
	"\vPutResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"F\n" +
	"\vGetResponse\x12!\n" +
	"\x06values\x18\x01 \x03(\v2\t.kv.ValueR\x06values\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"4\n" +
	"\fKeyHashEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"\x15\n" +
	"\x13GetKeyHashesRequest\"B\n" +
	"\x14GetKeyHashesResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.kv.KeyHashEntryR\aentries\"%\n" +
	"\x0fSyncKeysRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\x90\x01\n" +
	"\x10SyncKeysResponse\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.kv.SyncKeysResponse.DataEntryR\x04data\x1aH\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.kv.GetResponseR\x05value:\x028\x012\xbf\x02\n" +
	"\x02KV\x12&\n" +
	"\x03Put\x12\x0e.kv.PutRequest\x1a\x0f.kv.PutResponse\x12&\n" +
	"\x03Get\x12\x0e.kv.GetRequest\x1a\x0f.kv.GetResponse\x122\n" +
	"\tHintedPut\x12\x14.kv.HintedPutRequest\x1a\x0f.kv.PutResponse\x12;\n" +
	"\tHeartbeat\x12\x14.kv.HeartbeatMessage\x1a\x14.kv.HeartbeatMessage(\x010\x01\x12A\n" +
	"\fGetKeyHashes\x12\x17.kv.GetKeyHashesRequest\x1a\x18.kv.GetKeyHashesResponse\x125\n" +
	"\bSyncKeys\x12\x13.kv.SyncKeysRequest\x1a\x14.kv.SyncKeysResponseB#Z!github.com/pixperk/plethora/protob\x06proto3"

var (
	file_proto_kv_proto_rawDescOnce sync.Once
	file_proto_kv_proto_rawDescData []byte
)

func file_proto_kv_proto_rawDescGZIP() []byte {
	file_proto_kv_proto_rawDescOnce.Do(func() {
		file_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)))
	})
	return file_proto_kv_proto_rawDescData
}

var file_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_kv_proto_goTypes = []any{
	(*VectorClock)(nil),          // 0: kv.VectorClock
	(*Value)(nil),                // 1: kv.Value
	(*HeartbeatMessage)(nil),     // 2: kv.HeartbeatMessage
	(*PutRequest)(nil),           // 3: kv.PutRequest
	(*HintedPutRequest)(nil),     // 4: kv.HintedPutRequest
	(*PutResponse)(nil),          // 5: kv.PutResponse
	(*GetRequest)(nil),           // 6: kv.GetRequest
	(*GetResponse)(nil),          // 7: kv.GetResponse
	(*KeyHashEntry)(nil),         // 8: kv.KeyHashEntry
	(*GetKeyHashesRequest)(nil),  // 9: kv.GetKeyHashesRequest
	(*GetKeyHashesResponse)(nil), // 10: kv.GetKeyHashesResponse
	(*SyncKeysRequest)(nil),      // 11: kv.SyncKeysRequest
	(*SyncKeysResponse)(nil),     // 12: kv.SyncKeysResponse
	nil,                          // 13: kv.VectorClock.EntriesEntry
	nil,                          // 14: kv.SyncKeysResponse.DataEntry
}
var file_proto_kv_proto_depIdxs = []int32{
	13, // 0: kv.VectorClock.entries:type_name -> kv.VectorClock.EntriesEntry
	0,  // 1: kv.Value.clock:type_name -> kv.VectorClock
	1,  // 2: kv.PutRequest.value:type_name -> kv.Value
	1,  // 3: kv.HintedPutRequest.value:type_name -> kv.Value
	1,  // 4: kv.GetResponse.values:type_name -> kv.Value
	8,  // 5: kv.GetKeyHashesResponse.entries:type_name -> kv.KeyHashEntry
	14, // 6: kv.SyncKeysResponse.data:type_name -> kv.SyncKeysResponse.DataEntry
	7,  // 7: kv.SyncKeysResponse.DataEntry.value:type_name -> kv.GetResponse
	3,  // 8: kv.KV.Put:input_type -> kv.PutRequest
	6,  // 9: kv.KV.Get:input_type -> kv.GetRequest
	4,  // 10: kv.KV.HintedPut:input_type -> kv.HintedPutRequest
	2,  // 11: kv.KV.Heartbeat:input_type -> kv.HeartbeatMessage
	9,  // 12: kv.KV.GetKeyHashes:input_type -> kv.GetKeyHashesRequest
	11, // 13: kv.KV.SyncKeys:input_type -> kv.SyncKeysRequest
	5,  // 14: kv.KV.Put:output_type -> kv.PutResponse
	7,  // 15: kv.KV.Get:output_type -> kv.GetResponse
	5,  // 16: kv.KV.HintedPut:output_type -> kv.PutResponse
	2,  // 17: kv.KV.Heartbeat:output_type -> kv.HeartbeatMessage
	10, // 18: kv.KV.GetKeyHashes:output_type -> kv.GetKeyHashesResponse
	12, // 19: kv.KV.SyncKeys:output_type -> kv.SyncKeysResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_kv_proto_init() }
func file_proto_kv_proto_init() {
	if File_proto_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kv_proto_goTypes,
		DependencyIndexes: file_proto_kv_proto_depIdxs,
		MessageInfos:      file_proto_kv_proto_msgTypes,
	}.Build()
	File_proto_kv_proto = out.File
	file_proto_kv_proto_goTypes = nil
	file_proto_kv_proto_depIdxs = nil
}
